name: dogfooding


on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize]


jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install
      run: |
        yarn install --frozen-lockfile
      env:
        CI: true
    - name: Run test
      run: |
        yarn test
      env:
        CI: true
    - name: Run build
      run: yarn build
    - uses: ./
      id: coverage-history-action
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
